version: "3.9"

services:
  collector:
    image: otel/opentelemetry-collector-contrib
    command: [ --config=/etc/otel-collector-config.yaml ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
  app:
    build: .
    env_file: .env.${DOCKER_ENV:-local}
    command: ["npm", "run", "dev"]
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - collector
